# Generated by Django 4.2.27 on 2026-02-02 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('latitude', models.FloatField(default=35.6895, verbose_name='店舗の緯度')),
                ('longitude', models.FloatField(default=139.6917, verbose_name='店舗の経度')),
                ('day_change_time', models.TimeField(default='05:00', verbose_name='日付変更時間')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(verbose_name='業務日付')),
                ('clock_in_at', models.DateTimeField(blank=True, null=True, verbose_name='出勤時刻')),
                ('clock_out_at', models.DateTimeField(blank=True, null=True, verbose_name='退勤時刻')),
                ('status', models.CharField(choices=[('working', '勤務中'), ('finished', '退勤済'), ('correction_pending', '修正申請中')], default='working', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='スタッフ')),
            ],
        ),
    ]
