# Generated by Django 4.2.27 on 2026-02-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='break_end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='休憩終了'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='休憩開始'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('working', '勤務中'), ('on_break', '休憩中'), ('finished', '退勤済'), ('correction_pending', '修正申請中')], default='working', max_length=20),
        ),
    ]
